quarkus.langchain4j.ai.gemini.api-key=XXXXXXYour API Key hereXXXXXX
quarkus.langchain4j.ai.gemini.log-requests=true
quarkus.langchain4j.ai.gemini.log-responses=false
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-3-flash-preview
quarkus.langchain4j.ai.gemini.chat-model.thinking.thinking-budget=0
